name: random_models
channels:
  - conda-forge
dependencies:
  - ipykernel=6.26.0
  - matplotlib=3.8.1
  - mpmath=1.3.0
  - numpy=1.26.0
  - pandas=2.1.2
  - pip=23.3.1
  - python=3.12.0
  - requests=2.31.0
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - seaborn=0.13.2
  - sympy=1.12
  - tqdm=4.66.1
